# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: corentinlumineau
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskforce_development

test:
  <<: *default
  database: taskforce_test

production:
  <<: *default
  database: taskforce_production
  username: username
  password: <%= ENV['TASKFORCE_DATABASE_PASSWORD'] %>
